version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  nodejs2023q2-service:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs2023q2-service
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always

volumes:
  postgres-data: