version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    networks:
      - hls-network
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env.docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: existanz/hl-service
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hl-service
    depends_on:
      - postgres
    networks:
      - hls-network
    env_file:
      - .env.docker
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    restart: on-failure

networks:
  hls-network:
    name: hls-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${NET_SUBNET}
        ip_range: ${NET_IP_RANGE}
        gateway: ${NET_GATEWAY}
        aux_addresses:
          postgres: ${NET_POSTGRES_IP}
volumes:
  postgres-data: